import {useEffect,useMemo,useState} from "react";
import {BookOpen,Clock,Copy,Play,ShieldCheck,Trophy,Users} from "lucide-react";
import type {Book} from "../shared/types";
import {MAX_GAME_PLAYERS,READING_BUFFER_SECONDS} from "../shared/multiplayer";
import {expireMultiplayerPhase,advanceMultiplayerGame,answerMultiplayerQuestion,createMultiplayerGame,getMultiplayerState,joinMultiplayerGame,onlineErrorMessage,type MultiplayerState,listFriendConnections,inviteFriendToGame,listGameInvitations,dismissGameInvitation,type FriendConnection,type GameInvitation} from "./onlineService";

type BookMode="all"|"ot"|"nt"|"random"|"specific";
export default function CustomGame({books}:{books:Book[]}){
  const [roomCode,setRoomCode]=useState<string|null>(null),[joinCode,setJoinCode]=useState(""),[error,setError]=useState("");
  const [mode,setMode]=useState<BookMode>("all"),[selected,setSelected]=useState<string[]>([]),[randomCount,setRandomCount]=useState(5),[questionCount,setQuestionCount]=useState(10),[seconds,setSeconds]=useState(20),[busy,setBusy]=useState(false);
  const chosen=useMemo(()=>mode==="all"?books.map(b=>b.id):mode==="ot"?books.filter(b=>b.testament==="OT").map(b=>b.id):mode==="nt"?books.filter(b=>b.testament==="NT").map(b=>b.id):mode==="specific"?selected:books.map(b=>b.id).sort(()=>Math.random()-.5).slice(0,randomCount),[books,mode,selected,randomCount]);
  const run=async(action:()=>Promise<string>)=>{setBusy(true);setError("");try{setRoomCode(await action())}catch(e){setError(onlineErrorMessage(e,"Game setup failed."))}finally{setBusy(false)}};
  if(roomCode)return <GameRoom code={roomCode} leave={()=>setRoomCode(null)}/>;
  return <section className="custom-game">
    <div className="game-heading"><div><span className="eyebrow">LIVE CUSTOM QUIZ</span><h2>Host a Kahoot-style Bible game</h2><p>Invite up to {MAX_GAME_PLAYERS} signed-in players from your friends list or share a six-character room code.</p></div><span className="game-badge"><Users size={16}/> Up to 20 players</span></div>
    <GameInvitations join={code=>run(()=>joinMultiplayerGame(code))} busy={busy}/><div className="game-layout"><section className="game-builder card"><h3>Build your game</h3><fieldset><legend>Books in the quiz</legend><div className="choice-pills">{([['all','All 66'],['ot','Old Testament'],['nt','New Testament'],['random','Random books'],['specific','Choose books']] as [BookMode,string][]).map(([value,label])=><button className={mode===value?"selected":""} onClick={()=>setMode(value)} key={value}>{label}</button>)}</div></fieldset>
      {mode==="random"&&<label className="game-number">Number of random books<select value={randomCount} onChange={e=>setRandomCount(Number(e.target.value))}>{[1,3,5,10,15,20].map(n=><option key={n}>{n}</option>)}</select></label>}
      {mode==="specific"&&<div className="book-picker"><div><b>{selected.length} selected</b><button onClick={()=>setSelected(books.map(b=>b.id))}>Select all</button><button onClick={()=>setSelected([])}>Clear</button></div><div>{books.map(book=><label key={book.id}><input type="checkbox" checked={selected.includes(book.id)} onChange={()=>setSelected(current=>current.includes(book.id)?current.filter(id=>id!==book.id):[...current,book.id])}/>{book.name}</label>)}</div></div>}
      <div className="game-options"><label><span><BookOpen size={16}/>Questions</span><select value={questionCount} onChange={e=>setQuestionCount(Number(e.target.value))}>{[5,10,15,20].map(n=><option value={n} key={n}>{n}</option>)}</select></label><label><span><Clock size={16}/>Answer time</span><select value={seconds} onChange={e=>setSeconds(Number(e.target.value))}>{[10,15,20,30,45,60,90,120].map(n=><option value={n} key={n}>{n} seconds</option>)}</select></label></div>
      <div className="game-summary"><span>{chosen.length} book{chosen.length===1?"":"s"}</span><span>{questionCount} questions</span><span>{READING_BUFFER_SECONDS}s reading + {seconds}s answering</span></div>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={busy||!chosen.length} onClick={()=>void run(()=>createMultiplayerGame(chosen,questionCount,seconds))}>{busy?"Creating…":"Create game"}</button>
    </section><aside className="game-side"><section className="join-game card"><h3>Join a game</h3><p>Enter the leader’s room code.</p><div><input maxLength={6} value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())} placeholder="ABC123"/><button className="secondary" disabled={busy||joinCode.length!==6} onClick={()=>void run(()=>joinMultiplayerGame(joinCode))}>Join</button></div></section><section className="scoring-card card"><Trophy/><h3>Speed scoring</h3><strong>1,000 → 300</strong><p>Correct answers decrease evenly with time. Wrong answers earn zero.</p></section></aside></div>
  </section>;
}

function GameRoom({code,leave}:{code:string;leave:()=>void}){
  const [game,setGame]=useState<MultiplayerState|null>(null),[error,setError]=useState(""),[now,setNow]=useState(Date.now());
  const load=()=>getMultiplayerState(code).then(setGame).catch(e=>setError(onlineErrorMessage(e,"Game disconnected.")));
  useEffect(()=>{void load();const poll=setInterval(()=>void load(),750),clock=setInterval(()=>setNow(Date.now()),200);return()=>{clearInterval(poll);clearInterval(clock)}},[code]);
  const elapsed=game?.phaseStartedAt?Math.max(0,(now-new Date(game.phaseStartedAt).getTime())/1000):0;
  const phaseLimit=game?.status==="reading"?game.readingSeconds:game?.status==="answering"?game.questionSeconds:0;
  useEffect(()=>{
    if(!game?.host||!phaseLimit||elapsed<phaseLimit)return;
    let active=true,inFlight=false;
    const expire=async()=>{if(inFlight)return;inFlight=true;try{await expireMultiplayerPhase(code,game.currentIndex,game.status);if(active)await load()}catch(e){if(active)setError(onlineErrorMessage(e,"Could not advance game."))}finally{inFlight=false}};
    void expire();const retry=setInterval(()=>void expire(),1000);
    return()=>{active=false;clearInterval(retry)};
  },[code,game?.host,game?.status,game?.currentIndex,phaseLimit,elapsed>=phaseLimit]);
  if(!game)return <section className="full-lobby card"><h2>Joining game {code}…</h2>{error&&<p className="form-error">{error}</p>}</section>;
  const act=()=>advanceMultiplayerGame(code).then(load).catch(e=>setError(onlineErrorMessage(e,"Could not advance game.")));
  if(game.status==="lobby")return <section className="full-lobby card"><span className="eyebrow">GAME LOBBY</span><h1>Room {code}</h1><button className="secondary" onClick={()=>void navigator.clipboard?.writeText(code)}><Copy size={15}/> Copy code</button>{game.host&&<InviteFriends code={code} players={game.players}/>}<div className="lobby-grid">{game.players.map(player=><div key={player.userId}><span>👤</span><b>{player.username}</b><small><ShieldCheck size={13}/>Ready</small></div>)}</div><div className="lobby-actions"><span>{game.players.length}/{MAX_GAME_PLAYERS} players</span>{game.host?<button className="primary" onClick={()=>void act()}><Play size={16}/> Start game</button>:<b>Waiting for the leader…</b>}<button className="secondary" onClick={leave}>Leave</button></div>{error&&<p className="form-error">{error}</p>}</section>;
  if(game.status==="finished")return <section className="game-results card"><Trophy/><h1>Final standings</h1><Standings game={game}/><button className="primary" onClick={leave}>Done</button></section>;
  if(game.status==="result")return <section className="round-result card"><span className={game.answer?.correct?"round-correct":"round-wrong"}>{game.answer?.correct?"✓":"×"}</span><h1>{game.answer?.correct?"Correct!":"Round complete"}</h1><strong>+{game.answer?.points??0}</strong>{game.question?.correctIndex!=null&&game.question.choices&&<p>Correct answer: {game.question.choices[game.question.correctIndex]}</p>}<Standings game={game}/>{game.host?<button className="primary" onClick={()=>void act()}>{game.currentIndex+1===game.questionCount?"Show final results":"Next question"}</button>:<p>Waiting for the leader…</p>}</section>;
  const remaining=Math.max(0,phaseLimit-elapsed),choices=game.question?.choices;
  return <section className="live-game card"><div className="live-top"><span>Question {game.currentIndex+1}/{game.questionCount}</span><strong><Clock/> {Math.ceil(remaining)}</strong></div><div className="timer-track"><i style={{width:`${phaseLimit?remaining/phaseLimit*100:0}%`}}/></div><span className="eyebrow">{game.status==="reading"?"READ THE QUESTION":"ANSWER NOW"}</span><h2>{game.question?.text}</h2>{game.status==="reading"&&<p>Read the choices. Answers unlock when the answer timer starts.</p>}{game.answer?<p>Answer locked in. Waiting for the round to end…</p>:<div className="live-choices">{choices?.map((choice,index)=><button disabled={game.status!=="answering"} onClick={()=>void answerMultiplayerQuestion(code,index).then(load).catch(e=>setError(onlineErrorMessage(e,"Answer failed.")))} key={index}><b>{String.fromCharCode(65+index)}</b>{choice}</button>)}</div>}<small>{game.question?.bookName} {game.question?.chapter}:{game.question?.verseStart}</small>{error&&<p className="form-error">{error}</p>}</section>;
}
function Standings({game}:{game:MultiplayerState}){return <div className="mini-standings">{game.players.map((player,index)=><div key={player.userId}><b>{index+1}</b><span>{player.username}</span><div className="standing-points">{game.status==="result"&&<small>+{(player.questionPoints??0).toLocaleString()} this question</small>}<strong>{player.score.toLocaleString()} pts</strong></div></div>)}</div>}

function InviteFriends({code,players}:{code:string;players:MultiplayerState["players"]}){
  const [friends,setFriends]=useState<FriendConnection[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const [sent,setSent]=useState<string[]>([]),[pending,setPending]=useState<string|null>(null);
  const load=async()=>{setLoading(true);setError("");try{setFriends((await listFriendConnections()).filter(f=>f.direction==="friend"))}catch(e){setError(onlineErrorMessage(e,"Could not load friends."))}finally{setLoading(false)}};
  useEffect(()=>{void load()},[code]);
  const invite=async(id:string)=>{setPending(id);setError("");try{await inviteFriendToGame(code,id);setSent(current=>[...current,id])}catch(e){setError(onlineErrorMessage(e,"Could not send invitation."))}finally{setPending(null)}};
  return <section className="game-friend-invites"><h3>Invite friends</h3><p>Friends can accept your invitation in their Games tab.</p>{loading?<p>Loading friends...</p>:friends.length===0&&!error?<p>No friends yet. Add friends in the Friends tab to invite them here.</p>:<div className="friend-list">{friends.map(friend=>{const joined=players.some(p=>p.userId===friend.userId),invited=sent.includes(friend.userId);return <div key={friend.userId}><div><b>{friend.username}</b></div><button className="secondary" disabled={pending!==null||joined||invited||players.length>=MAX_GAME_PLAYERS} onClick={()=>void invite(friend.userId)}>{joined?"Joined":pending===friend.userId?"Sending...":invited?"Invited":"Invite"}</button></div>})}</div>}{error&&<p role="alert" className="form-error">{error} <button className="secondary" onClick={()=>void load()}>Refresh friends</button></p>}</section>;
}

function GameInvitations({join,busy}:{join:(code:string)=>Promise<void>;busy:boolean}){
  const [items,setItems]=useState<GameInvitation[]>([]),[error,setError]=useState(""),[dismissing,setDismissing]=useState(false);
  useEffect(()=>{let active=true;const load=async()=>{try{const invitations=await listGameInvitations();if(active){setItems(invitations);setError("")}}catch(e){if(active)setError(onlineErrorMessage(e,"Could not load game invitations."))}};void load();const timer=setInterval(()=>void load(),5000);return()=>{active=false;clearInterval(timer)}},[]);
  const dismiss=async(id:string)=>{setDismissing(true);try{await dismissGameInvitation(id);setItems(current=>current.filter(i=>i.id!==id))}catch(e){setError(onlineErrorMessage(e,"Could not dismiss invitation."))}finally{setDismissing(false)}};
  return <section className="game-friend-invites card"><h3>Game invitations</h3>{error&&<p className="form-error" role="alert">{error}</p>}{!items.length&&!error&&<p>Invitations from friends will appear here.</p>}<div className="friend-list">{items.map(item=><div key={item.id}><div><b>{item.username}</b><small>Invited you to room {item.code}</small></div><button className="primary" disabled={busy||dismissing} onClick={()=>void join(item.code)}>Join game</button><button className="secondary" disabled={busy||dismissing} onClick={()=>void dismiss(item.id)}>Dismiss</button></div>)}</div></section>;
}
